using System;
using Microsoft.EntityFrameworkCore.Migrations;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NsStore.Infrastructure.Persistence.Migrations
{
    /// <summary>
    /// Introduces the branch dimension. The scaffolded order was rewritten by hand: the generated
    /// version added NOT NULL columns defaulted to 0 and then pointed foreign keys at a table that
    /// did not exist yet, which fails on any database that already holds rows.
    /// </summary>
    /// <remarks>
    /// <para><b>This migration is one-way in practice.</b> <c>Down</c> restores the schema, but it
    /// cannot restore the old one-row-per-product uniqueness once a second branch has stock — it
    /// will fail on the primary key. Treat a rollback as "restore from backup".</para>
    /// <para>Migrations run at API startup unless <c>Database:MigrateOnStartup</c> is false, so
    /// deploy this one with the store closed.</para>
    /// </remarks>
    public partial class AddBranches : Migration
    {
        /// <summary>Tables that gain a branch_id, in dependency-free order.</summary>
        private static readonly string[] BranchedTables =
        [
            "stock_levels", "inventory_movements", "sales", "purchases",
            "users", "payments", "orders", "quotes"
        ];

        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            // 1. The table itself.
            migrationBuilder.CreateTable(
                name: "branches",
                columns: table => new
                {
                    id = table.Column<long>(type: "bigint", nullable: false)
                        .Annotation("Npgsql:ValueGenerationStrategy", NpgsqlValueGenerationStrategy.IdentityByDefaultColumn),
                    code = table.Column<string>(type: "character varying(8)", maxLength: 8, nullable: false),
                    name = table.Column<string>(type: "character varying(120)", maxLength: 120, nullable: false),
                    address = table.Column<string>(type: "character varying(200)", maxLength: 200, nullable: true),
                    phone = table.Column<string>(type: "character varying(40)", maxLength: 40, nullable: true),
                    is_active = table.Column<bool>(type: "boolean", nullable: false),
                    sale_sequence = table.Column<long>(type: "bigint", nullable: false),
                    purchase_sequence = table.Column<long>(type: "bigint", nullable: false),
                    transfer_sequence = table.Column<long>(type: "bigint", nullable: false),
                    created_by = table.Column<long>(type: "bigint", nullable: true),
                    created_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: false),
                    updated_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true),
                    deleted_at = table.Column<DateTimeOffset>(type: "timestamp with time zone", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("pk_branches", x => x.id);
                });

            migrationBuilder.CreateIndex(name: "ix_branches_code", table: "branches", column: "code");

            // 2. Case-insensitive uniqueness, raw so the model differ never sees it — same
            //    precedent as the lower(username) index in the initial schema.
            migrationBuilder.Sql(
                "CREATE UNIQUE INDEX ux_branches_code_active ON branches (lower(code)) WHERE deleted_at IS NULL;");

            // 3. Seed the default branch with an explicit id 1, so every later step is a constant.
            //    Raw SQL rather than HasData: EF tracks seeded rows in the snapshot forever and
            //    would re-diff them against the AuditableEntity timestamps on every future migration.
            //    The column is GENERATED BY DEFAULT, so an explicit id needs no OVERRIDING clause;
            //    setval keeps the identity sequence in step so the next insert does not collide.
            migrationBuilder.Sql(
                """
                INSERT INTO branches (id, code, name, is_active, sale_sequence, purchase_sequence, transfer_sequence, created_at)
                VALUES (1, 'MAIN', 'Casa Matriz', true, 0, 0, 0, now());

                SELECT setval(pg_get_serial_sequence('branches','id'), 1, true);
                """);

            // 4. Add the column nullable. On PG 11+ that is metadata only, so it is instant.
            foreach (var table in BranchedTables)
            {
                migrationBuilder.AddColumn<long>(name: "branch_id", table: table, type: "bigint", nullable: true);
            }

            // 5. Backfill. Raw SQL deliberately bypasses the query filters: soft-deleted rows need
            //    the value too.
            foreach (var table in BranchedTables)
            {
                migrationBuilder.Sql($"UPDATE {table} SET branch_id = 1 WHERE branch_id IS NULL;");
            }

            // 6. Now it can be NOT NULL.
            foreach (var table in BranchedTables)
            {
                migrationBuilder.AlterColumn<long>(
                    name: "branch_id",
                    table: table,
                    type: "bigint",
                    nullable: false,
                    oldClrType: typeof(long),
                    oldType: "bigint",
                    oldNullable: true);
            }

            // 7. Foreign keys.
            foreach (var table in BranchedTables)
            {
                migrationBuilder.AddForeignKey(
                    name: $"fk_{table}_branches_branch_id",
                    table: table,
                    column: "branch_id",
                    principalTable: "branches",
                    principalColumn: "id",
                    onDelete: ReferentialAction.Restrict);
            }

            // 8. Rebuild the stock key. A table has exactly one primary key, so the old one has to
            //    go first. Dropping it leaves fk_stock_levels_products_product_id without a backing
            //    index until the third statement — which cross-branch reads want anyway.
            migrationBuilder.DropPrimaryKey(name: "pk_stock_levels", table: "stock_levels");
            migrationBuilder.AddPrimaryKey(
                name: "pk_stock_levels",
                table: "stock_levels",
                columns: ["branch_id", "product_id"]);
            migrationBuilder.CreateIndex(
                name: "ix_stock_levels_product_id", table: "stock_levels", column: "product_id");

            // 9. Densify the grid: every (branch × live product) pair owns a row, because
            //    SELECT … FOR UPDATE only locks rows that exist. Nearly a no-op with one branch,
            //    but it is the same statement BranchService.CreateAsync runs, so writing it here
            //    validates it.
            migrationBuilder.Sql(
                """
                INSERT INTO stock_levels (branch_id, product_id, quantity, updated_at, version)
                SELECT b.id, p.id, 0, now(), 0
                FROM branches b CROSS JOIN products p
                WHERE p.deleted_at IS NULL
                  AND NOT EXISTS (SELECT 1 FROM stock_levels s WHERE s.branch_id = b.id AND s.product_id = p.id);
                """);

            // 10. Query indexes.
            migrationBuilder.CreateIndex(
                name: "ix_users_branch_id", table: "users", column: "branch_id");
            migrationBuilder.CreateIndex(
                name: "ix_payments_branch_id", table: "payments", column: "branch_id");
            migrationBuilder.CreateIndex(
                name: "ix_orders_branch_id", table: "orders", column: "branch_id");
            migrationBuilder.CreateIndex(
                name: "ix_quotes_branch_id", table: "quotes", column: "branch_id");
            migrationBuilder.CreateIndex(
                name: "ix_sales_branch_id_sale_date",
                table: "sales",
                columns: ["branch_id", "sale_date"]);
            migrationBuilder.CreateIndex(
                name: "ix_purchases_branch_id_purchase_date",
                table: "purchases",
                columns: ["branch_id", "purchase_date"]);
            migrationBuilder.CreateIndex(
                name: "ix_inventory_movements_branch_id_product_id_created_at",
                table: "inventory_movements",
                columns: ["branch_id", "product_id", "created_at"]);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropIndex(name: "ix_inventory_movements_branch_id_product_id_created_at", table: "inventory_movements");
            migrationBuilder.DropIndex(name: "ix_purchases_branch_id_purchase_date", table: "purchases");
            migrationBuilder.DropIndex(name: "ix_sales_branch_id_sale_date", table: "sales");
            migrationBuilder.DropIndex(name: "ix_quotes_branch_id", table: "quotes");
            migrationBuilder.DropIndex(name: "ix_orders_branch_id", table: "orders");
            migrationBuilder.DropIndex(name: "ix_payments_branch_id", table: "payments");
            migrationBuilder.DropIndex(name: "ix_users_branch_id", table: "users");

            // Only rows of the original branch can survive a single-column primary key. Anything
            // else makes the AddPrimaryKey below fail — see the remarks on the class.
            migrationBuilder.Sql("DELETE FROM stock_levels WHERE branch_id <> 1;");

            migrationBuilder.DropIndex(name: "ix_stock_levels_product_id", table: "stock_levels");
            migrationBuilder.DropPrimaryKey(name: "pk_stock_levels", table: "stock_levels");

            foreach (var table in BranchedTables)
            {
                migrationBuilder.DropForeignKey(name: $"fk_{table}_branches_branch_id", table: table);
                migrationBuilder.DropColumn(name: "branch_id", table: table);
            }

            migrationBuilder.AddPrimaryKey(name: "pk_stock_levels", table: "stock_levels", column: "product_id");

            migrationBuilder.Sql("DROP INDEX IF EXISTS ux_branches_code_active;");
            migrationBuilder.DropTable(name: "branches");
        }
    }
}
